# Generated by Django 3.0.4 on 2020-11-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_machine_dsw',
            old_name='Client',
            new_name='Client_ID_Code',
        ),
        migrations.AddField(
            model_name='rent_machine_dsw',
            name='Time_Usage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
